name: Node CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node@16
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn
      - run: yarn run build

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node@16
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn
      - run: yarn run test

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node@16
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn
      - run: yarn run lint
